### ISSUE TITLE
VPS Odoo Server Timeouts and Shuts Down After Some Time

### ISSUE THREAD

**Issue by realChainLife** [mtsoftware2016/odoo-13#3]
Hi, I used the 18.04 installation guide to set up an odoo server on a digital ocean vps. Guide works great and i was able to launch the server on a browser. Now however i need to login to the console terminal and run `sudo systemctl start odoo13` a few times a day because the server automatically times and shuts down. I'm using / 8 GB Memory / 160 GB Disk / FRA1 - Ubuntu 19.04 x64, so its not a memory issue.

**Comment by mtsoftware2016** [comment]
Hello, thank your for contact us.
Can we talk on skype will be better.
Cordially Mt software.

Le mer. 11 déc. 2019 à 7:41 AM, Sonia John <notifications@github.com> a
écrit :
